### ISSUE TITLE
I cannot subscribe topics except /mavros/state

### ISSUE THREAD

**Issue by Student865** [vacabun/offboard-control#1]
Hello, I'm using mavros with ROS2 foxy. I can only subscribe the topic "/mavros/state", but other topics such as "/mavros/local_position/pose" and "/mavros/altitude" cannot be subscribed. I can use "ros2 topic echo" to get these topics, and I use "rqt_graph" and find that my node is really subscribing these topics. I notice that my code is very likely to yours, so I‘d like to ask if you have met the same problem before

**Comment by vacabun** [comment]
Are you using the ros2 version of mavros?

**Comment by vacabun** [comment]
Did you use the [Launch Files](https://github.com/mavlink/mavros/tree/ros2/mavros#launch-files)？
